Below is an explanation of `defaultdict` in Python
```python
# Importing the defaultdict class from collections module
from collections import defaultdict

# Function to return a default value for missing keys
def default_value():
    return "Key Not Found"

# Creating a defaultdict with default_value function as default_factory
dd = defaultdict(default_value)

# Adding some key-value pairs to the dictionary
dd['a'] = 1
dd['b'] = 2

# Accessing an existing key and a missing key
print(dd['a'])  # Output: 1
print(dd['b'])  # Output: 2
print(dd['c'])  # Output: Key Not Found
```

### Explanation:
- `defaultdict` is a subclass of the built-in `dict` class.
- It overrides one method and adds one writable instance variable.
- The main feature of `defaultdict` is that it provides a default value for missing keys.
- If you try to access or modify a key that doesn't exist, `defaultdict` will automatically create the key and assign it the default value provided by a function you set at its initialization (known as `default_factory`).
- This avoids the need to check for the existence of a key and is useful in many scenarios where dictionaries are used for counting or grouping operations.

### How it works:
- When you access `dd['c']`, which is not present in the dictionary, the `default_factory` function `default_value` is called to provide a default value, which is "Key Not Found" in this case.
- This behavior prevents a `KeyError` that would normally occur with a standard dictionary.

### When to use `defaultdict`:
- It's particularly useful when you need a dictionary to represent a collection of items where each key has multiple values.
- It simplifies the code by eliminating the need for initial checks or try/except blocks to handle missing keys.

Remember, `defaultdict` is part of the `collections` module, so you need to import it before using it.

Source: Conversation with Copilot, 6/4/2024
(1) Defaultdict in Python - GeeksforGeeks. https://www.geeksforgeeks.org/defaultdict-in-python/.
(2) Using the Python defaultdict Type for Handling Missing Keys. https://realpython.com/python-defaultdict/.
(3) defaultdict in Python - Analytics Vidhya. https://www.analyticsvidhya.com/blog/2024/01/defaultdict-in-python/.
(4) Python defaultdict | Usage, Examples, and Alternatives. https://ioflood.com/blog/python-defaultdict/.


Certainly! Let's explore `defaultdict(float)` and `defaultdict(int)` in Python, which are special cases of the `defaultdict` class where the `default_factory` is set to `float` and `int`, respectively.

### `defaultdict(float)`
When you initialize a `defaultdict` with `float` as the `default_factory`, it means that any time you access a key that doesn't exist in the dictionary, it will automatically create the key with a default value of `0.0` (the default value returned by calling `float()` with no arguments).

Here's an example in a Jupyter Notebook format:

```python
from collections import defaultdict

# Creating a defaultdict with float as default_factory
dd_float = defaultdict(float)

# Accessing a missing key
print(dd_float['missing_key'])  # Output: 0.0

# The missing key is now added to the dictionary with default value 0.0
print(dd_float)  # Output: defaultdict(<class 'float'>, {'missing_key': 0.0})
```

### `defaultdict(int)`
Similarly, when you initialize a `defaultdict` with `int` as the `default_factory`, any missing key accessed will be created with a default value of `0` (the default value returned by calling `int()` with no arguments).

Here's how it looks:

```python
from collections import defaultdict

# Creating a defaultdict with int as default_factory
dd_int = defaultdict(int)

# Accessing a missing key
print(dd_int['missing_key'])  # Output: 0

# The missing key is now added to the dictionary with default value 0
print(dd_int)  # Output: defaultdict(<class 'int'>, {'missing_key': 0})
```

### Summary:
- `defaultdict(float)` and `defaultdict(int)` are convenient when you need a dictionary that automatically initializes missing keys with a default numeric value (`0.0` for float and `0` for int), which is particularly useful for numerical computations and counters.
- They save you from having to check if a key exists before using it, thus making your code cleaner and more efficient.

Source: Conversation with Copilot, 6/4/2024
(1) Defaultdict in Python - GeeksforGeeks. https://www.geeksforgeeks.org/defaultdict-in-python/.
(2) Using the Python defaultdict Type for Handling Missing Keys. https://realpython.com/python-defaultdict/.
(3) python defaultdict: 0 vs. int and [] vs list - Stack Overflow. https://stackoverflow.com/questions/10788378/python-defaultdict-0-vs-int-and-vs-list.
(4) Python Collections — DefaultDict : Dictionary with Default ... - Medium. https://medium.com/swlh/python-collections-defaultdict-dictionary-with-default-values-and-automatic-keys-305540540d2a.
(5) How to use defaultdict in Python - Accelebrate. https://www.accelebrate.com/blog/using-defaultdict-python.
(6) python - Defaultdict with values defaulted to negative infinity - Stack .... https://stackoverflow.com/questions/29901564/defaultdict-with-values-defaulted-to-negative-infinity.

In [10]:
import gym
import pandas as pd
import numpy as np 
from collections import defaultdict
from pprint import pprint
import tqdm
env= gym.make("Blackjack-v1")

def policy(state_user_sum):
    return 0 if state_user_sum>19 else 1

def generate_episode(policy,env=env):
    episode=[]
    state,_= env.reset()
    while True:
        action= policy(state[0])
        next_state,reward, done, info,_ = env.step(action=action)
        episode.append((state,action,reward))
        if done : break
        state= next_state
    return episode

In [11]:
state,_= env.reset()
print (state)
print(policy(state[0]))
episode=generate_episode(policy)
print(episode)

(17, 10, False)
1
[((16, 6, False), 1, 0.0), ((19, 6, False), 1, -1.0)]

c:\Users\roozu\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):

In [12]:


def every_vist(number_of_iteration=3*500000):
    total_return = defaultdict(float)
    N = defaultdict(int)

    # tqdm.trange is a version of the built-in range function that includes a progress bar
    for i in tqdm.trange(number_of_iteration):
        episode = generate_episode(policy)
        states, actions, rewards = zip(*episode)

        for t, state in enumerate(states):
            N[state] = N[state] + 1
            if state not in states[0:t]:
                R = (sum(rewards[t:]))
                total_return[state] = total_return[state] + R

    return total_return, N

def first_vist(number_of_iteration=3*500000):
    total_return = defaultdict(float)
    N = defaultdict(int)

    # tqdm.trange is a version of the built-in range function that includes a progress bar
    for i in tqdm.trange(number_of_iteration):
        episode = generate_episode(policy)
        states, actions, rewards = zip(*episode)

        for t, state in enumerate(states):
            
            if state not in states[0:t]:
                N[state] = N[state] + 1
                R = (sum(rewards[t:]))
                total_return[state] = total_return[state] + R

    return total_return, N

In [13]:
total_return, N = every_vist()
total_return_df= pd.DataFrame(total_return.items(),columns=["state","total_return"])
N_df= pd.DataFrame(N.items(), columns=["state","N"])
df= pd.merge(total_return_df,N_df, on="state")
df["value"]= df["total_return"]/df['N']
df.head()

100%|██████████| 1500000/1500000 [02:19<00:00, 10764.66it/s]

            state  total_return      N     value
0  (16, 4, False)      -10319.0  15472 -0.666947
1  (19, 4, False)      -12158.0  16638 -0.730737
2  (16, 1, False)      -11434.0  15666 -0.729861
3  (21, 1, False)        7364.0  11431  0.644213
4  (14, 9, False)       -8645.0  14672 -0.589218

In [14]:
total_return, N = first_vist()
total_return_df_1= pd.DataFrame(total_return.items(),columns=["state","total_return"])
N_df_1= pd.DataFrame(N.items(), columns=["state","N"])
df_1= pd.merge(total_return_df_1,N_df_1, on="state")
df_1["value"]= df["total_return"]/df['N']
df_1.head()

100%|██████████| 1500000/1500000 [02:23<00:00, 10478.16it/s]

            state  total_return      N     value
0  (18, 3, False)      -11649.0  16438 -0.666947
1   (16, 8, True)        -671.0   1864 -0.730737
2   (17, 8, True)        -815.0   2062 -0.729861
3  (14, 8, False)       -8605.0  14624  0.644213
4  (19, 8, False)      -12000.0  16834 -0.589218

In [15]:
df.head(1000)

              state  total_return      N     value
0    (16, 4, False)      -10319.0  15472 -0.666947
1    (19, 4, False)      -12158.0  16638 -0.730737
2    (16, 1, False)      -11434.0  15666 -0.729861
3    (21, 1, False)        7364.0  11431  0.644213
4    (14, 9, False)       -8645.0  14672 -0.589218
..              ...           ...    ...       ...
275   (4, 9, False)        -273.0    666 -0.409910
276   (4, 5, False)        -292.0    668 -0.437126
277   (4, 4, False)        -347.0    739 -0.469553
278   (12, 5, True)        -155.0    691 -0.224313
279   (4, 3, False)        -306.0    649 -0.471495

[280 rows x 4 columns]

In [16]:
print( df[   df["state"]==(21,8,False)    ]["value"])
print( df_1[   df_1["state"]==(21,8,False)    ]["value"])

121    0.929421
Name: value, dtype: float64
90   -0.092846
Name: value, dtype: float64